spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_store
    username: root
    password: Rayyan2504
    driver-class-name: com.mysql.jdbc.Driver
  graphql:
    graphiql:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
